GET http://localhost:3001/api/classes

###########################
POST http://localhost:3001/api/classes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNWI1MTg0YzRlNzI4ZmI4MzAzMWE4ZSIsImVtYWlsIjoibWF0aWFzdmlvbGEwMkBnbWFpbC5jb20iLCJpYXQiOjE2NjY5MjkwNDh9.njHvywqJ2qckapPpZsOnJNuO4PTElTcFM8hDEl3oirM

{
    "nombre": "Guitarra Para Principiantes",
    "descripcion": "Aprende paso a paso a tocar la guitarra. Aprende tocando y olvidate de ejercicios aburridos",
    "tipoClase": "individual",
    "frecuencia": "semanal",
    "calificacion": 0,
    "esNueva": true,
    "duracion": 1,
    "costo": 100,
    "srcImagen": "https://guitarraviva.b-cdn.net/wp-content/uploads/2015/09/stock-nylon-bossa_67587098.jpg",
    "materia":6
}

##############################
DELETE http://localhost:3001/api/classes/635c2721b18edc1b535400b0

###############
GET http://localhost:3001/api/classes/635c27c4387ea5f33d976b7f
