GET http://localhost:3001/api/profesors

###########################
POST http://localhost:3001/api/profesors
Content-Type: application/json

{
    "idUsuario":"635b57c51455153d46ed68b0",
    "titulo":"Licenciatura en Matematicas",
    "experiencia":"Sin experiencia pero con ganas"
}
